branches:
  only:
  - master

language: node_js

node_js:
  - '9'

sudo: false

matrix:
  include:
    - os: linux
    - os: mac
    - os: windows

env:
  - YARN_GPG=no
  
install:
  - npm install 
  - (cd e2e ; npm install)

script:
  - npm run compile
  - npm run test
  - npm run e2e
  - npm run lint

after_failure:
  - cat e2e/server-fixture/server.log
